/*
 * Experimental ROBOT plugin
 * Copyright © 2026 Damien Goutte-Gattat
 * 
 * This program is free software; you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the Gnu General Public License
 * along with this program. If not, see <http://www.gnu.org/licenses/>.
 */

package org.incenp.obofoundry.robot;

import java.io.BufferedReader;
import java.io.FileReader;
import java.io.IOException;
import java.util.HashSet;
import java.util.Set;

import org.apache.commons.cli.CommandLine;
import org.obolibrary.robot.CommandState;
import org.semanticweb.owlapi.model.IRI;
import org.semanticweb.owlapi.model.OWLAnnotationAssertionAxiom;
import org.semanticweb.owlapi.model.OWLAxiom;
import org.semanticweb.owlapi.model.OWLDataFactory;
import org.semanticweb.owlapi.model.OWLOntology;

/**
 * A command to attempt to automatically fix the most trivial issues revealed by
 * the <code>report</code> command.
 * <p>
 * In the context of this command, “trivial“ issues are issues that should not
 * require manual intervention on each affected term. For now, this means the
 * “obsolete missing label” issue and the “lowercase definition” issue.
 */
public class FixRobotReportCommand extends BasePlugin {

    public FixRobotReportCommand() {
        super("fix-robot-report", "fix trivial errors revealed by the report command",
                "robot fix-robot-report --input <FILE> --robot-report <FILE> --output <FILE>");

        options.addOption(null, "robot-report", true, "the file generated by the report command");
    }

    @Override
    public void performOperation(CommandState state, CommandLine line) throws Exception {
        if ( !line.hasOption("robot-report") ) {
            throw new Exception("Missing required option --robot-report");
        }
        Set<Error> errors = parseRobotReport(line.getOptionValue("robot-report"));

        OWLOntology ont = state.getOntology();
        OWLDataFactory fac = ont.getOWLOntologyManager().getOWLDataFactory();
        HashSet<OWLAxiom> toRemove = new HashSet<>();
        HashSet<OWLAxiom> toAdd = new HashSet<>();

        for ( Error error : errors ) {
            for ( OWLAnnotationAssertionAxiom ax : ont.getAnnotationAssertionAxioms(error.subject) ) {
                if ( ax.getProperty().getIRI().equals(error.property) ) {
                    if ( ax.getValue().isLiteral() ) {
                        String oldValue = ax.getValue().asLiteral().get().getLiteral();
                        String newValue = null;
                        switch ( error.type ) {
                        case LOWERCASE_DEFINITION:
                            newValue = Character.toUpperCase(oldValue.charAt(0)) + oldValue.substring(1);
                            break;
                        case MISSING_OBSOLETE_LABEL:
                            newValue = "obsolete " + oldValue;
                            break;
                        default:
                            break;
                        }

                        if ( newValue != null ) {
                            OWLAxiom newAx = fac.getOWLAnnotationAssertionAxiom(
                                    fac.getOWLAnnotationProperty(error.property), error.subject,
                                    fac.getOWLLiteral(newValue));
                            toAdd.add(newAx.getAnnotatedAxiom(ax.getAnnotations()));
                            toRemove.add(ax);
                        }
                    }
                }
            }
        }

        ont.getOWLOntologyManager().removeAxioms(ont, toRemove);
        ont.getOWLOntologyManager().addAxioms(ont, toAdd);
    }

    private Set<Error> parseRobotReport(String file) throws IOException {
        HashSet<Error> errors = new HashSet<>();
        BufferedReader reader = new BufferedReader(new FileReader(file));

        String line = null;
        while ( (line = reader.readLine()) != null ) {
            String[] items = line.split("\t");
            if ( items.length < 4 ) {
                continue;
            }
            if ( items[1].equals("lowercase_definition") ) {
                errors.add(new Error(ErrorType.LOWERCASE_DEFINITION, items[2], items[3]));
            } else if ( items[1].equals("missing_obsolete_label") ) {
                errors.add(new Error(ErrorType.MISSING_OBSOLETE_LABEL, items[2], items[3]));
            }
        }
        reader.close();

        return errors;
    }

    private class Error {
        ErrorType type;
        IRI subject;
        IRI property;

        public Error(ErrorType type, String subject, String property) {
            this.type = type;
            this.subject = ioHelper.createIRI(subject);
            this.property = ioHelper.createIRI(property);
        }
    }

    private enum ErrorType {
        MISSING_OBSOLETE_LABEL,
        LOWERCASE_DEFINITION
    }

}
